### ISSUE TITLE
使用settings.json的时候出现错误提示

### ISSUE THREAD

**Issue by cuteJaven** [EthanDeng/vscode-latex#11]
`latex-workshop.latex.autoBuild.onSave.enabled` and `latex-workshop.latex.autoBuild.onTexChange.enabled` have been replaced by `latex-workshop.latex.autoBuild.run`, which is set to `never`.  Please manually remove the deprecated configs from your `settings.json`

**Comment by EthanDeng** [comment]
说的是 settings 已经被替换为新设置了，你先按照这个来改，之后我更新到 settings.json 。
