### ISSUE TITLE
"latex-workshop.latex.autoBuild.onSave.enabled"不可用

### ISSUE THREAD

**Issue by XAjzh** [EthanDeng/vscode-latex#3]
刚才在配置 VS Code，发现 settings.json 中的
"latex-workshop.latex.autoBuild.onSave.enabled"不可用，
这个命令好像被 "latex-workshop.latex.autoBuild.run" 所取代。
我下载的 LaTeX Workshop 是 7.0.0 版本。

**Comment by EthanDeng** [comment]
嗯 这个是过时的，之后我会更新。

**Comment by EthanDeng** [comment]
已经删除。
