### ISSUE TITLE
我按main.pdf中的介绍配置后，外部PDF阅读器不可用

### ISSUE THREAD

**Issue by XAjzh** [EthanDeng/vscode-latex#4]
我在 setting.json 中单独配置 "latex-workshop.view.pdf.viewer": "external",不起作用，
另外尝试过将SumatraPDF所在路径加入path，也不起作用。
额外配置 "latex-workshop.view.pdf.external.command": {
        "command": "C:\\Program Files\\SumatraPDF\\SumatraPDF",
        "args": [
            "%PDF%"
        ]
    },
后才可使用外置PDF阅读器浏览。

**Comment by EthanDeng** [comment]
我这边没问题，我的配置只有下面这几句（除去 latex tools 和 receipts：

```json
{
    "window.zoomLevel": -1,
    "latex-workshop.view.pdf.viewer": "external",
    "editor.fontFamily": "FiraMono, '文泉驿等宽微米黑','Courier New', monospace",
    "editor.fontSize": 16,
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "One Dark Pro",
```

**Comment by XAjzh** [comment]
可能是我之前没配置好，我注释了 "latex-workshop.view.pdf.external.command" 这一部分也可以用了。
那就这样了。
