### ISSUE TITLE
main.pdf 文件的配置代码中引号是错的

### ISSUE THREAD

**Issue by XAjzh** [EthanDeng/vscode-latex#6]
不知道是什么原因， main.tex 中是英文的引号，但是 main.pdf 里好像不是，直接复制 main.pdf 中的配置代码不能用。

**Comment by EthanDeng** [comment]
嗯 main.pdf 中引号是中文，main.tex 中引号是英文的..

**Comment by EthanDeng** [comment]
已经修正。
